### ISSUE TITLE
Misalignment of the main header

### ISSUE THREAD

**Issue by voline** [Philip-Scott/Notes-up#10]
Header with double hash ##
![image](https://cloud.githubusercontent.com/assets/17718635/13674037/f3ab11ac-e701-11e5-9c04-2be494f1bc8c.png)
 
with single hash #
![image](https://cloud.githubusercontent.com/assets/17718635/13674058/063e6c56-e702-11e5-9efc-4252acaf4613.png)

The title shifts to the center for the main header as you can see. Looks to me like a bug.
Id, wish something could be done to make the font consistent too but I guess that has nothing to do with the application.

**Comment by Philip-Scott** [comment]
Since it's an "elementary app", the default stylesheet is based upon elementary's website: https://elementary.io/docs/human-interface-guidelines#human-interface-guidelines 

I am working on a way for you to be able to set custom stylesheets using CSS from within the app though :) That's coming soon ;)

**Comment by Philip-Scott** [comment]
@voline  Alright! Version 1.1 is out! You should be able to soon `apt-get upgrade` it  :smile: 

Once you have the newest version, open the preferences dialog via the gear button, go to the viewer section and copy this there: 
```h1 {
	text-align: left;
}```

**Comment by voline** [comment]
Thanks, great work.
