### ISSUE TITLE
Feature request: Cloud backup

### ISSUE THREAD

**Issue by megatux** [Philip-Scott/Notes-up#134]
I try to avoid apps that do not _auto-save/backup_ on the cloud. G.Drive, Dropbox or OneDrive. This probably should be an integrated service on the OS but in the meantime I guess it could be done independently.

**Comment by proxycyber** [comment]
Agreed. Can I ask how you'd manually back up notes, though? I can't seem to figure it out.

**Comment by Philip-Scott** [comment]
Closing since it's a dup of #70. I would love to, but sadly i don't think there's an API for those, and i also wouldn't want to force someone into using a certain platform. 

the `/home/YOURNAME/.local/share/notes-up/NotesUp.db` file has your notes, so you could back that up with your favorite service for now :)
