### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by sschuhmann** [Philip-Scott/Notes-up#171]
Would it be possible to use an icon which fits better to the default elementary style icons compared in size?

The current icon is higher than all other icons.

![screenshot from 2017-08-20 13 49 06](https://user-images.githubusercontent.com/7888383/29494615-7a34561a-85ae-11e7-9f1d-f4df4e74034b.png)

**Comment by Philip-Scott** [comment]
This is actually not a problem since it's the same size as the other tall icons:

![screenshot from 2017-08-20 12 10 22](https://user-images.githubusercontent.com/10786508/29496846-9232c0c0-85a0-11e7-9685-cab52e4afd1a.png)

It's even documented in https://elementary.io/docs/human-interface-guidelines#composition on the exceptions part :)

**Comment by sschuhmann** [comment]
Thanks, did't know there are app icons in different sizes
