### ISSUE TITLE
Feature request: Latex equation support

### ISSUE THREAD

**Issue by RTbecard** [Philip-Scott/Notes-up#172]
Is this already implemented, or being planned on added in the near future?

**Comment by proxycyber** [comment]
Sounds like a neat idea, I hope this will come to life.

**Comment by dgdav99** [comment]
Has this feature already been implemented?

**Comment by acolombier** [comment]
I did implement this feature on my fork, using Mathjax, but the PR had been rejected because of the heaviness of the JS library.

**Comment by dgdav99** [comment]
@acolombier Cool. I'll try that out

**Comment by acolombier** [comment]
@dgdav99 let me know if you encounter any problems!

**Comment by RTbecard** [comment]
Since this is labeled "out of scope", should I expect that latex support is not being considered here?

I really implore you to add some sort of latex support to this, without it, you're excluding a large user base of students/academics who rely on latex for writing out equations..

PS, @acolombier very cool!  I be sure to give your fork a try!

**Comment by Philip-Scott** [comment]
@RTbecard I'm not going to add it myself, and I'm also not going to add thousands of lines and files of JavaScript. Since at the end of the day markdown is just html you can always just add your own script tags. If someone else codes latex support in either C or Vala I'll add it. But you can see why im against it in the PR #254
