### ISSUE TITLE
Anyway to relocate datebase file to second HDD?

### ISSUE THREAD

**Issue by TechRage** [Philip-Scott/Notes-up#211]
Great work on the app! I just start using it and I have to say it came to be more useful than I initially thought. 

I have a second hard drive on my laptop and I want Notes-Up save and read the Notesup.db file from that drive instead. Is there a way for me to do that? I know I can copy the file, but it to do that every time I I make a new page.

Thanks in advance.

**Comment by ar0ra1** [comment]
with the dconf editor you can change the location of the database
if that solves your issue

`org -> notes`

**Comment by worldofpeace** [comment]
There really needs to be a feature in which you can export your local data. I think there has been other issues on this same topic. I don't remember exactly what @Philip-Scott said though. :)

**Comment by bobsobol** [comment]
Nice tip from ar0ra1, but there is a solution which works for any program, even if not as well written as Notes-up.

TachRage: the default location is `~/.local/share/notes-up/NotesUp.db`. So you can _always_ just:-
```
mv ~/.local/share/notes-up/NotesUp.db /mnt/second_drive
ln /mnt/second_drive/NotesUp.db ~/.local/share/notes-up/NotesUp.db
```
With the assumption that you have mounted your second drive / partition / filesystem volume (or possibly network drive / NAS / SAN / cloud storage etc.) at `/mnt/second_drive`. You can also do this from the Pantheon file browser in elementaryOS, by shift dragging the NotesUp.db file to your second drive, (to move it) then alternate (usually right button) dragging it back, and selecting "Link Here", to create the link.

Be aware, that the Notes-up database is **secure** in your home directory, and _very secure_ if your home directory is encrypted. If you link to a Notes-up database on a public / shared location, (even if that is encrypted) that security will become less to minimal, and in a very non-obvious way. That won't matter if it's your desktop computer, and you are the only real user, but if you're on a portable device, (laptop / tablet) public, or corporate network machine, that may significantly change the nature of the information you want to store _in it_. (think GDPR) The file it's self is an unencrypted sqlight database.

Also be aware that you will introduce potential instability. (just by using a second drive, regardless of the method used to achieve that aim) If the second drive is not _always_ mounted, (in `/etc/fstab` for example) or becomes "offline" due to an error elsewhere, (cloud / network storage in a network outage situation f.e., or just a failed 2nd local disk) and you open Notes-up one day without noticing that the second drive isn't mounted... Results will be unpredicted, but certainly undesirable. Of course, if the primary drive went down with it on, you wouldn't be booting your OS at all, I'm just pointing out that you shift the point of failure in ways which can be confusing to debug down the road when you have forgotten how (or even _that_)  you moved the file. :wink:
