### ISSUE TITLE
Enabling <Del> for trashing a project section

### ISSUE THREAD

**Issue by fbruetting** [Philip-Scott/Notes-up#217]
Doesn’t work right now… ;)

**Comment by Philip-Scott** [comment]
You should be more specific with your issues ;) 

Do you mean typing the Del key? Also keep in mind that we don't want pages being deleted by accident. That's why deleting only works in Edit mode, and we can't really use del in this mode since the key can be used for text editing.

Ctrl+Del also isn't an option ;)

**Comment by fbruetting** [comment]
Alright, sounds reasonable. :)
