### ISSUE TITLE
Relative paths for images?

### ISSUE THREAD

**Issue by DroWnThePoor** [Philip-Scott/Notes-up#229]
Is it not possible to use relative paths for images?
I've moved my database to a Nextcloud shared folder, Nextcloud allows me to paste entire web articles
and automatically saves all the images to /media subfolder and all images get the file://media/etc... link,
I tried to move the database the the notes directory that contains /media to have this work automatically
in Notes-Up, and I've even tried ./media/ /media/ and media/ but the only thing that works is writing the 
full path.

Either way, this is probably the best markdown editor I've found. I started using this on Elementary before it was even published in Appcenter, and I was overjoyed to find it in the AUR as well! Thank you.

**Comment by Philip-Scott** [comment]
Sadly, if i made relative images work, it would break being able to grab an image from anywhere on the computer, so i'm not going to fix it :/ 

BUT! If instead of dragging and dropping an image, you click on the image button on the taskbar, a file selection dialog will appear, and the image you choose from there will be imported into the database, and you'll be able to open that from any computer :)
