### ISSUE TITLE
Tutorial: Translating into a new language

### ISSUE THREAD

**Issue by mcarlo95** [Philip-Scott/Notes-up#248]
Hello, I just faced two annoying bugs when using notes-up on an Italian system.
First is that hunspell-it was not installed by default so I could not see spellcheck.
Second and more serious is the one about exporting to PDF. I read in issues that a translation is needed to fix that bug (was not easy to find out). Hopefully a better solution will be available with time, for now I can happily translate everything in Italian.
Where should I start?

**Comment by Philip-Scott** [comment]
Hey! Thank you very much for volunteering to contribute with the translations :) There is a program you can install from the terminal called `poedit`, and you can use it to create your language's `.po`  file using this as a template: https://github.com/Philip-Scott/Notes-up/blob/master/po/notes-up.pot

Once you have it, simply make a PR with your file and i'll be able to merge it! :) 

About hunspell-it not being installed, this isn't really a problem with your installation or the app. It's just that we can't really include all the spellcheck languages in the world by default on every system, but those should be installable from your elementary system settings on the language part. 

_closing the issue since the questions has been answered_

**Comment by mcarlo95** [comment]
Great! I will eventually do a PR tomorrow. One more question for the translation.
The work Notebook is more like: a) school notebook b) notepad c) diary (moleskine)
There is also a pic to help you choose the italian word you like more: [Imgur](https://i.imgur.com/oo9SFrp.png)  😃

**Comment by Philip-Scott** [comment]
The Spanish translation uses the word for "School Notebook", so i think it would be fine to use that one :smile: 

Thanks for asking!
