### ISSUE TITLE
Issue with "&"

### ISSUE THREAD

**Issue by infosisio** [Philip-Scott/Notes-up#284]
When using the "&" character as the first header, which becomes the note title, if you then view that note in the Window title you will see it rendered as ";amp" and not as "&".

**Comment by infosisio** [comment]
@Philip-Scott Line 259 in Services/Page.vala is causing this.

**Comment by Philip-Scott** [comment]
If you want to fix it, you can also fix it by setting the property of the header's title `use_markup` to `true` :) escaping the characters is needed to prevent other sorts of problems

**Comment by infosisio** [comment]
@Philip-Scott Well, you are better suited to update it in the main repo so that all users can enjoy the fix :)

**Comment by Philip-Scott** [comment]
@infosisio if you want you can do it as well, and make a PR :)

**Comment by infosisio** [comment]
@Philip-Scott Thanks for the spirit - Vala proficiency is not under my belt yet, hence my suggestion.

**Comment by Philip-Scott** [comment]
If you want to learn, it's actually a super simple fix :) This issue is a super good one to be able to learn the basics on how things work!

This is the Headerbar class: 
https://github.com/Philip-Scott/Notes-up/blob/master/src/Widgets/Headerbar.vala

And here's the class info for HeaderBars from Gtk:
https://valadoc.org/gtk+-3.0/Gtk.HeaderBar.html

try with the function `get_custom_title ()` in there and see if it returns the label widget, if it does then it should be super easy to cast the widget to a label and set the property `((Gtk.Label) widget).use_markup`

 If not then you need to make a new Label widget, and add it to the class using `set_custom_title ()` :)

**Comment by infosisio** [comment]
@Philip-Scott It's not that it seems hard or anything but I usually avoid touching FOSS projects if I am not proficient in the respective language.

**Comment by Philip-Scott** [comment]
I don't really mind :) I love helping people get started. If you really don't want to do it no worries, but i still think that if you want to lean Vala, this is a really good issue to try to tackle

**Comment by infosisio** [comment]
@Philip-Scott Yeah I really appreciate your intention ! Thanks for trying to help.

**Comment by Philip-Scott** [comment]
fixed in 2679615
