### ISSUE TITLE
Proposal: Real time preview

### ISSUE THREAD

**Issue by FDiskas** [Philip-Scott/Notes-up#323]
Hi,
thanks for nice app. I suggest to add ability to preview the current note on the right side of the edit section. Also with scroll in sync
Currently preview available on double click.

It would be cool to have ability to see how it looks. And also would be nice see bolded text as bold right away in the editor like in screenshot.

![image](https://user-images.githubusercontent.com/468006/56363311-94ed3980-61f4-11e9-84d4-c2616f36f609.png)

Working example https://stackedit.io/app

**Comment by Philip-Scott** [comment]
The code for a dual panel mode is now up! Fixed in e94b4dd

I'm still not 100% certain about the UX for selecting dual pane mode :thinking: Maybe i'll set it as a quick settings setting instead, so it may change before the next release is done.

For now though, here is a preview of the paned view:
![image](https://user-images.githubusercontent.com/10786508/58444236-d9ee7080-80bc-11e9-9002-2a64b6e612bb.png)

Note: It's not a 100% live preview as it's too expensive an operation to keep doing all the time. But it will be triggered every minute while typing, or when you press Ctrl+S to save.

**Comment by FDiskas** [comment]
I suggest preview on right side. Because left side is more like working space
