### ISSUE TITLE
[Feature] Allow the user to find the directory where to save notes and keep them in .md files

### ISSUE THREAD

**Issue by luisnando** [Philip-Scott/Notes-up#36]
It would be nice to access my notes from other computers and from my cell. The simplest way would be to allow the notes to be saved in a directory of my choice. The subdirectories could respect the notebooks hierarchy as well. Keep images and .md files within each folder and thats it.

Would you consider something similar? Keep up! Great application!

**Comment by Philip-Scott** [comment]
Actually, a long time ago (before the first release) i had a folder button you could access from the pages list: 

![original build](https://cloud.githubusercontent.com/assets/10786508/14584294/691b0e5e-0405-11e6-9c62-5eb6207ec6eb.png)

but..... I later decided against letting the normal user access it's contents. If you really really **really** need to change the save directory, you can do it via dconf. But for the rest of the users, the app is meant for you to be able to simply write things down without having to worry about files. 

About keeping Images within the folder.... maybe ;) I'll think about that, specially since deleting them would be an issue after a while since like i said, a normal user wouldn't be having access to the files

 For now though, you can add images via drag'n'drop, or even link to images right from the web if you copy it's web address, and in the 1.2 release you'll be able to get an OpenFile dialog to select an image to link to

**Comment by luisnando** [comment]
Thanks for the reply! And how would you suggest be the best approach to backup the notes? A cronjob that copies the files elsewere? A symlink to my dropbox folder?

Thanks

**Comment by Philip-Scott** [comment]
You can do it as you wish :) All your notes are being stored currently as one folder per notebook or section, and one file per page, so you can easily do what you want with them. iirc, the notes folder is either in ~/.notes or ~/.local/share/notes, so you can either add it to the folders you want to sync with dropbox, or just change it's save directory right from dconf
