### ISSUE TITLE
The select color changes back to black

### ISSUE THREAD

**Issue by igomezal** [Philip-Scott/Notes-up#4]
When I create a New Notebook and i select the color, i have to edit it so it select the color and it saves it.

And well...
I don't know if it is a bug but when i open the window to create a new notebook and then i open another program the window to create the new notebook keeps at the front until i cancel it or i create a new notebook.

Cheers

**Comment by Philip-Scott** [comment]
Dialogs being always on top IS a "bug," but i again cannot confirm your first bug about creating Notebooks not using the selected color on the first try, and switching to black :/ It's working fine here on my end...

Do you mind updading this and your previous bug report with either a terminal output, or a step by step of what you do to reproduce them? :) Else, you might have a bug with the way your system is configured because it's working fine on a clean system

**Comment by igomezal** [comment]
Hello this is the output when i create a new notebook:
`ivan@ivan-Notebook:~$ notes-up 

(Notes:3012): Gtk-CRITICAL **: gtk_window_set_focus: assertion 'gtk_widget_get_can_focus (focus)' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`
I just click on New Notebook and then select the name and the color.

**Comment by Philip-Scott** [comment]
@igomezal Hey Ivan, do you still have the problem occurring? 

I really haven't being able to duplicate it, so i'm going to mark it as closed. But if you still have the problem, feel free to re-open it! :smiley:

**Comment by igomezal** [comment]
@Philip-Scott Well I still have this problem even after the update but thanks for your help, maybe it's my system's problem and have nothing to do with the application.
