### ISSUE TITLE
Ability to use markup with keyboard commands

### ISSUE THREAD

**Issue by yerbestpal** [Philip-Scott/Notes-up#41]
For example, ctrl+b for **bold**, etc. This would really speed up the note-taking process.

**Comment by yerbestpal** [comment]
Also, some sort of help section detailing said commands would have to accompany the feature.

**Comment by Philip-Scott** [comment]
Yeah, i agree :+1: And actually, it's something i'm planning for the next release ;) 

Although i'm not sure if Ctrl+B should set both sets of ** and put the cursor in the middle, or just one set, and have to ctrl+b again to close it.... Now, instead of a help section, i was thinking of adding them to the button's tooltips, i think that would integrate better with the current ui :)

- [ ] Create shortcuts for the tool items 
- [ ] Show them in the UI

Thank you for your feedback!

**Comment by yerbestpal** [comment]
Agreed; tooltips would work better. I think Having the command have ** at both ends works better. Obviously it minimises the amount of keystrokes and it'd make for quicker note-taking. If there were some way where a command would add the open **, and not add the closing one until hitting 'space' to move on, that'd be pretty great. It'd mean that you could nest the markup.
