### ISSUE TITLE
Checklist item

### ISSUE THREAD

**Issue by tatsuhirosatou** [Philip-Scott/Notes-up#68]
It would be great if it supported check list items, [like Github itself](https://github.com/blog/1825-task-lists-in-all-markdown-documents). This would allow you to also use this app as a todo app.

**Comment by Philip-Scott** [comment]
What i can do easily is add support so that `- [x]` and `- [ ] ` shows as their respective buttons, but clicking on them would have no effect (It would need a mayor backend re-write to be able to do so....) 

But if you really want a TODO app, check out [Go For It!](https://github.com/mank319/Go-For-It). It's another great app made for elementary (It's the one I use that almost every day :wink:)

**Comment by tatsuhirosatou** [comment]
Thanks for your reply! In that case it would a bit backward to use it for that use case, I will check out that app you mentioned.
