### ISSUE TITLE
be nicer to the filesystem for git

### ISSUE THREAD

**Issue by Nine-H** [Philip-Scott/Notes-up#82]
I have a notes repo at https://github.com/Nine-H/ITECH2017-Notes

this workflow is pretty nice for sharing notes with classmates but there's a few issues:

1. putting all the data at the end of the filename is uggersAF
2. files should have a .md extension so they can be viewed formatted from github
3. might be nice to integrate git into the app, but not necessary

I'll try to keep you posted on what else goes wrong.

**Comment by Philip-Scott** [comment]
@Nine-H Yeah, i agree it was ugly AF, but it being like that made sure files didn't collision and caused problems.

But actually, the newest version completely ditches the file system in favor of a database for storing the data. I am thinking of adding a way to export complete notebooks as either PDF, HTML or the raw markdown as the .md

If you want to try the new version, you have to add the newest repo :wink:

**Comment by Nine-H** [comment]
shit, there goes my workflow. roughly what revision would `notes-up/xenial,now 0.1-0~20+r1~ubuntu0.4.1 amd64 [installed] be?`

**Comment by Philip-Scott** [comment]
Heh :sweat_smile: that's the reason i didn't push the update on the old repo 

[Rhis is the last commit](https://github.com/Philip-Scott/Notes-up/tree/6487c25b393ee7cd7bca92512b0c31ece4dc2449) before i started switching to using a database for saving everything! 

Although, if you can I would switch to it sooner rather than later. There are some really cool features coming soon like being able to store images with the Page (As well as being able to edit it using your favorite app such as gimp/inkscape) and being able to sort by different things such as modification date, or by title. And some more plug-ins ;) 

And you'll be able to export your notes anyway to different formats such as HTML (And using github-pages, you can have your own "website" with your notes)

**Comment by Nine-H** [comment]
all good, these things happen.

what's the (very rough) eta on being able to dump .md so I can maintain continuity for the people that read off my notes? do you have a plan for importing notes? I like to use git to sync between my notebook and my desktop too, is there a way to do that or will I have to dick around with elementary sharing settings?

**Comment by Philip-Scott** [comment]
If both computers run elementary, you should be able to sync the database file with something like dropbox (Or even github, although it won't be pretty) 

Importing could work, but i think i would make it so it imports to a new Notebook since overwriting won't end up well (And would like to figure out #23 first so moving notes isn't a pain)

But i'm thinking on having exporting done this week, depending on how busy school and work gets.

**Comment by Nine-H** [comment]
I really don't want to fork, but I liked flat files because I could use source code tools to manage them, version control them, and work on them in a distributed way. I guess you're not moving back for the forseeable future. shit. I might have to. does the new revis do file association and work as a general .md editor?

**Comment by Philip-Scott** [comment]
It does not. But if what you want is a pure markdown editor, there is one made by another elementary dev:  https://github.com/voldyman/MarkMyWords
